[versions]
# Стабильные версии
agp = "8.5.1"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"
timber = "5.0.1"

# Android
compileSdk = "34"
minSdk = "24"
targetSdk = "34"

# Библиотеки
coreKtx = "1.12.0"
lifecycle = "2.7.0"
navigation = "2.7.7"
room = "2.6.1"
hilt = "2.50"
coroutines = "1.7.3"
gson = "2.10.1"

# Jetpack Compose
compose-bom = "2024.05.00"
compose-compiler = "1.5.11"
activity-compose = "1.8.2"
navigation-compose = "2.7.7"
hilt-navigation-compose = "1.2.0"
coil = "2.5.0"
material3 = "1.2.1"
material = "1.11.0"
compose-material = "1.6.3"

# Testing
junit = "4.13.2"
extJunit = "1.1.5"
espresso = "3.5.1"

[libraries]
# Base
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

# Lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material" }

# Other
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

material = { module = "com.google.android.material:material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


[bundles]
compose = [
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling-preview",
    "compose-material3",
    "activity-compose",
    "navigation-compose",
    "compose-material-icons-extended"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }